# Config overrides for production.
url: https://alexmanrique.com
analytics:
  provider: custom
  google:
    tracking_id: G-79GL8C39KM
comments:
  provider: disqus
  disqus:
    shortname: disqus_ToBQPiwQxS